### ISSUE TITLE
kernel concurrency - question 

### ISSUE THREAD

**Issue by ramcn** [enzorucci/SWIFOLD#2]
Hello,

One question I had after studying the paper and code is about kernel concurrency. With the current version of the code using a single device and wgsize of 1 in 3d, i presume only one instance of the kernel will be running at a time.

If I need to run this for performance, I believe I need to change the NDRange (wgsize and gsize) parameters to extract maximum concurrency. Please let me know if this understanding is correct.

Thanks,
Ram

**Comment by enzorucci** [comment]
Hi Ram.

Only one instance of the kernel will be running at a time with this version of the code. However, this is not a serial kernel. Take into account that when you use the task parallel model (single work-item, single work-group), the Intel-Altera OpenCL Compiler extracts efficient loop parallelism, which allows the loops to execute in a true pipeline fashion. 

From the "OpenCL extension on Intel’s FPGA" section in the SWIFOLD paper:
_At the moment of selecting a parallel programming model, Intel FPGA OpenCL SDK [26] recommends the task parallel model as the best performance choice. We should point out that the AOC extracts efficient loop parallelism, which allows the loop to execute in a true pipeline fashion._

From the "SW Implementation" section:
_From the performance point of view, fully unrolling the inner loop represents an essential aspect of this kernel since this technique allows the AOC to exploit loop instruction pipelining._ 

In addition, you can find more information in the programming and optimization guides for Intel FPGA SDK for OpenCL.

So you do not need to change to a NDRange kernel for performance. Just use this kernel tuning the BLOCK_WIDTH constant according to the available resources. Remeber that this constant has a strong influence on both performance and resource usage (see "Results and Discussion" section from the SWIFOLD paper).

Enzo

**Comment by ramcn** [comment]
Thank you for the detailed explanation. That clarifies.
